language: python
python:
  - "3.6"

install:
  - pip install mypy
  - pip install mypy_extensions
  - pip install xml2rfc
  - pip install typeguard
  - gem install --no-doc kramdown-rfc2629

script:
  - pip install hacspec-py/
  - make -C hacspec-py
  - travis_wait 40 make -C specs -j10
  - make -C spec-compilers
  - make -C rfc
