language: python
sudo: required
python:
  - "3.6.4"

services:
  - docker

install:
  - pip install typeguard
  - pip install Sphinx
  - pip install mypy # for typed_ast

jobs:
  include:
    - stage: build
      name: python build
      script:
        - make -C build test
    - stage: docs
      name: docs
      script:
        - make python-docs
    # TODO: get hugo on here.
    # -
    #   name: website
    #   script:
    #     - make website
    - stage: "test & typecheck"
      name: run
      script: make run
    -
      name: checkspec
      script: make check
    -
      name: test typechecked
      script: make test
    # Typecheck slow specs.
    # Kyber is too slow for travis :(
    # -
    #   name: test kyber
    #   script: make kyber-test
    # WOTS is way too slow for travis as well :(
    # -
    #   name: test wots
    #   script: make wots-test
    -
      name: test argon2i
      script: make argon2i-test
    # Run OCaml compiler and FStar compilation in docker.
    -
      name: compiler
      install: skip
      script:
        - docker run -v $PWD:/home/worker/_hacspec --rm -ti franziskus/hacspec:0.3 /home/worker/_hacspec/docker/travis-compiler/run.sh
