baseURL = "https://hacs-workshop.github.io/hacspec"
languageCode = "en-us"
title = "hacspec"
theme = "ananke"

enableRobotsTXT = true
SectionPagesMenu = "main"

[params]
  description = "the new specification language for crypto primitives"
  github = "https://github.com/HACS-workshop/hacspec/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
